<?php

namespace App\HttpController;

use EasySwoole\Http\AbstractInterface\Controller;
use EasySwoole\Template\Render;
use http\Url;

class Base extends Controller
{
    public function index()
    {

    }

    /**
     * Overrides
     * Base constructor.
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Overrides
     * @param null|string $action
     * @return bool|null
     */
    protected function onRequest(?string $action): ?bool
    {
        $bool = parent::onRequest($action); // TODO: Change the autogenerated stub
        if ($bool === false) return false;

        return true;
    }

    /**
     * Overrides
     * @param \Throwable $throwable
     * @throws \Throwable
     */
    protected function onException(\Throwable $throwable): void
    {
        parent::onException($throwable); // TODO: Change the autogenerated stub
    }

    /**
     * Overrides
     * @param null|string $action
     */
    protected function actionNotFound(?string $action)
    {
        parent::actionNotFound($action); // TODO: Change the autogenerated stub
        $this->response()->withStatus(404);
        $file = EASYSWOOLE_ROOT . '/vendor/easyswoole/easyswoole/src/Resource/Http/404.html';
        if (!is_file($file)) {
            $file = EASYSWOOLE_ROOT . '/src/Resource/Http/404.html';
        }
        $this->response()->write(file_get_contents($file));
    }

}